version: '3.8'

services:
  whispering-orchids:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  # Development service
  whispering-orchids-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5179:5179"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    profiles:
      - dev